name: Publish to PyPI

on:
  create:
    tags:
      - "*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install --upgrade setuptools twine

      - name: Build source distribution
        run: python setup.py sdist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --skip-existing dist/*
